name: "new CMIP7 experiment"
description: "Configure a CMIP7 experiment"
title: "DO NOT USE, WILL BE OVERWRITTEN!"
body:
  - type: dropdown
    id: compset
    attributes:
      label: Experiment compset
      multiple: false
      options:
        - piControl, concentration driven (N1850)
        - piControl, emissions driven (N1850ems)
        - historical, concentration (NHIST)
        - historical, emissions (NHISTems)
        - N2000
        - N2000ems
        - ssp999
    validations:
      required: true
  - type: dropdown
    id: resolution
    attributes:
      label: Experiment resolution (grid)
      multiple: false
      options:
        - ne30pg3_tn14
        - ne16pg3_tn14
    validations:
      required: true
  - type: dropdown
    id: run_type
    attributes:
      label: Experiment run time
      multiple: false
      options:
        - initial
        - branch
        - hybrid
    validations:
      required: true
  - type: input
    id: RUN_REFCASE
    attributes:
      label: RUN_REFCASE
      description: Location of a branch or hybrid dataset (RUN_REFCASE), if applicable
      placeholder: ex. /cluster/projects/nn0000k/...
    validations:
      required: false
  - type: input
    id: RUN_REFDATE
    attributes:
      label: RUN_REFDATE
      description: Restart date for a branch or hybrid run (RUN_REFDATE), if applicable
      placeholder: ex. 0046-01-01
    validations:
      required: false
  - type: dropdown
    id: project
    attributes:
      label: Project number
      multiple: false
      options:
        - NN9560K
      default: 0
    validations:
      required: true
