name: "new CMIP7 experiment"
description: "Configure a CMIP7 experiment"
title: "DO NOT USE, WILL BE OVERWRITTEN!"
body:
  - type: dropdown
    id: compset
    attributes:
      label: Experiment compset
      multiple: false
      options:
        - piControl, concentration driven (N1850)
        - piControl, emissions driven (N1850ems)
        - historical, concentration (NHIST)
        - historical, emissions (NHISTems)
        - N2000
        - N2000ems
        - ssp999
    validations:
      required: true
  - type: dropdown
    id: resolution
    attributes:
      label: Experiment resolution (grid)
      multiple: false
      options:
        - ne30pg3_tn14
        - ne16pg3_tn14
    validations:
      required: true
  - type: dropdown
    id: run_type
    attributes:
      label: Experiment run time
      multiple: false
      options:
        - initial
        - branch
        - hybrid
    validations:
      required: true
