name: "new CMIP7 experiment"
description: "Configure a CMIP7 experiment"
title: "DO NOT USE, WILL BE OVERWRITTEN!"
body:
  - type: dropdown
    id: compset
    attributes:
      label: Experiment compset
      multiple: false
      options:
        - N1850: (piControl, concentration driven)
        - N1850Esm: (piControl, emissions driven)
        - NHist: (historical, concentration driven)
        - NHistEsm: (historical, emissions driven)
        - N2000
        - N2000Ems
        - ssp999
    validations:
      required: true
  - type: dropdown
    id: resolution
    attributes:
      label: Experiment resolution (grid)
      multiple: false
      options:
        - ne30pg3_tn14
        - ne16pg3_tn14
    validations:
      required: true
  - type: dropdown
    id: run_type
    attributes:
      label: Experiment run type
      multiple: false
      options:
        - initial
        - branch
        - hybrid
    validations:
      required: true
  - type: input
    id: run_startyear
    attributes:
      label: Case start year
      description: Case start year
      placeholder: e.g., 0000, 1850
    validations:
      required: false
  - type: input
    id: run_stopyear
    attributes:
      label: Case stop year
      description: Case stop year
      placeholder: e.g., 0300, 2010
    validations:
      required: false
  - type: input
    id: RUN_REFCASE
    attributes:
      label: RUN_REFCASE
      description: Location of a branch or hybrid dataset (RUN_REFCASE), if applicable
      placeholder: ex. /cluster/projects/nn0000k/...
    validations:
      required: false
  - type: input
    id: RUN_REFDATE
    attributes:
      label: RUN_REFDATE
      description: Restart date for a branch or hybrid run (RUN_REFDATE), if applicable
      placeholder: ex. 0046-01-01
    validations:
      required: false
  - type: input
    id: RUN_REFTOD
    attributes:
      label: RUN_REFTOD
      description: Restart time of day for a branch or hybrid run (RUN_REFTOD), if applicable
      value: "00000"
    validations:
      required: false
  - type: input
    id: SRC_TAG
    attributes:
      label: Source tag
      description: NorESM tag for experiment source code
    validations:
      required: true
  - type: dropdown
    id: machine
    attributes:
      label: Case machine
      multiple: false
      options:
        - Betzy
        - Olivia
    validations:
      required: true
  - type: dropdown
    id: project
    attributes:
      label: Project number
      multiple: false
      options:
        - NN9560K
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: "---"
  - type: markdown
    attributes:
      value: "## Do not enter anything below, this section is automated"
